title: Notes and Things

description: <3
theme: minima
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.linkedin.com/in/susanacdelgadillo/"
github_username:  susana

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

timezone: America/New_York
